apiVersion: v1
kind: PersistentVolumeClain
metadata:
  name: mysl-dados
spec:
  accessMode:
    - ReadWriteOnce
  resources: 
    requests:
      storage: 10Gi
  storageClassName: standard-rwo


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: docker push luminato/projeto-database:1.0
        args: "--ignore-db-dir=lost+found"
        imagePullPolicy: Always
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql

        volumeMounts:
        - name: mysql-dados
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-dados
        persistentVolumeClain:
          claimName: mysql-dados

---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: php
  labels:
    app: php
spec:
  replicas: 6
  selector: 
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: docker push luminato/projeto-backend:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80

